Repository Developers-Adgitm/Projects, pull requests merged in 2023-10, with the labels that each got.

#25 new project - downloadify
  Projects/downloadify/README.md
  Projects/downloadify/backend/downloader.py
  Projects/downloadify/backend/main.py
  Projects/downloadify/backend/requirements.txt
  Projects/downloadify/backend/scrapeURL.py
  Projects/downloadify/frontend/YTDownloader.js
  Projects/downloadify/frontend/index.html
  Projects/downloadify/frontend/package-lock.json
  Projects/downloadify/frontend/package.json
  Projects/downloadify/frontend/public/homePage/background.jpg
  Projects/downloadify/frontend/public/homePage/logo-removebg-preview.png
  Projects/downloadify/frontend/public/homePage/logo.png
  Projects/downloadify/frontend/public/homePage/phone-background.jpg
  Projects/downloadify/frontend/public/homePage/step1.jpg
  Projects/downloadify/frontend/public/homePage/step2.jpg
  Projects/downloadify/frontend/public/homePage/step3.jpg
  Projects/downloadify/frontend/public/vite.svg
  Projects/downloadify/frontend/src/App.css
  Projects/downloadify/frontend/src/App.jsx
  Projects/downloadify/frontend/src/components/download/Downloader.jsx
  Projects/downloadify/frontend/src/components/download/downloadMechanics.js
  Projects/downloadify/frontend/src/components/header/Header.jsx
  Projects/downloadify/frontend/src/components/home/index.css
  Projects/downloadify/frontend/src/components/home/index.jsx
  Projects/downloadify/frontend/src/components/home/searchBar.jsx
  Projects/downloadify/frontend/src/components/videoPage/fromSearch.jsx
  Projects/downloadify/frontend/src/components/videoPage/fromURL.jsx
  Projects/downloadify/frontend/src/components/videoPage/mainBox.jsx
  Projects/downloadify/frontend/src/components/videoPage/video.css
  Projects/downloadify/frontend/src/components/videoPage/videoPage.css
  Projects/downloadify/frontend/src/components/videoPage/videoPreview.jsx
  Projects/downloadify/frontend/src/main.jsx
  Projects/downloadify/frontend/vercel.json
  Projects/downloadify/frontend/vite.config.js
  Projects/downloadify/frontend/yarn.lock
Labels: documentation

#23 New Project
  Projects/ifeelgreen.github.io-main/app.js
  Projects/ifeelgreen.github.io-main/dashboard/dashboard.html
  Projects/ifeelgreen.github.io-main/dashboard/script.js
  Projects/ifeelgreen.github.io-main/dashboard/styledash.css
  Projects/ifeelgreen.github.io-main/dashboard/weather/app.js
  Projects/ifeelgreen.github.io-main/dashboard/weather/custon.css
  Projects/ifeelgreen.github.io-main/dashboard/weather/weather.htm
  Projects/ifeelgreen.github.io-main/dgb.jpg
  Projects/ifeelgreen.github.io-main/fashion/index.html
  Projects/ifeelgreen.github.io-main/img/advantage.webp
  Projects/ifeelgreen.github.io-main/img/advantages.jpg
  Projects/ifeelgreen.github.io-main/img/doctor.jpg
  Projects/ifeelgreen.github.io-main/img/farming.jpg
  Projects/ifeelgreen.github.io-main/img/farming2.jpg
  Projects/ifeelgreen.github.io-main/img/farming3.jpg
  Projects/ifeelgreen.github.io-main/img/organic.png
  Projects/ifeelgreen.github.io-main/img/problem.webp
  Projects/ifeelgreen.github.io-main/img/tomato.jpg
  Projects/ifeelgreen.github.io-main/index.html
  Projects/ifeelgreen.github.io-main/registaratinstyle.css
  Projects/ifeelgreen.github.io-main/register.html
  Projects/ifeelgreen.github.io-main/registerjs.js
  Projects/ifeelgreen.github.io-main/style.css
Labels: enhancement

#33 Update projects.js
  projects.js
Labels: hacktoberfest-accepted

#36 Smart Scientific Calculator
  Projects/Scientific Calculator/calculator_img.png
  Projects/Scientific Calculator/main.py
  Projects/Scientific Calculator/mic_img.png
  Projects/Scientific Calculator/music1.wav
  Projects/Scientific Calculator/music2.wav
Labels: good first issue, hacktoberfest-accepted

#39 Add files via upload
  Projects/SoulBound_Confession/css/bootstrap.min.css
  Projects/SoulBound_Confession/css/pogo-slider.min.css
  Projects/SoulBound_Confession/css/responsive.css
  Projects/SoulBound_Confession/css/responsiveslides.css
  Projects/SoulBound_Confession/css/style.css
  Projects/SoulBound_Confession/images/apple-touch-icon.png
  Projects/SoulBound_Confession/images/blog-img-01.jpg
  Projects/SoulBound_Confession/images/blog-img-02.jpg
  Projects/SoulBound_Confession/images/blog-img-03.jpg
  Projects/SoulBound_Confession/images/favicon.ico
  Projects/SoulBound_Confession/images/footer-bg.jpg
  Projects/SoulBound_Confession/images/logo.png
  Projects/SoulBound_Confession/images/menu-arrow.png
  Projects/SoulBound_Confession/images/pexels-los-muertos-crew-6836692-1920x1080-24fps.mp4
  Projects/SoulBound_Confession/images/ptn-bg.jpg
  Projects/SoulBound_Confession/images/slider-01.jpg
  Projects/SoulBound_Confession/images/slider-02.jpg
  Projects/SoulBound_Confession/images/tag-line.png
  Projects/SoulBound_Confession/index.html
  Projects/SoulBound_Confession/js/bootstrap.min.js
  Projects/SoulBound_Confession/js/images-loded.min.js
  Projects/SoulBound_Confession/js/jquery.min.js
  Projects/SoulBound_Confession/js/jquery.pogo-slider.min.js
  Projects/SoulBound_Confession/js/main.js
  Projects/SoulBound_Confession/js/responsiveslides.min.js
  Projects/SoulBound_Confession/js/slider-index.js
Labels: good first issue, hacktoberfest-accepted

#40 IMPROVED DOCUMENTATION OF PROJECTS
  Projects/README.md
Labels: documentation, hacktoberfest-accepted

#43 Request for new project : Toxicity Grading Model using TensorFlow and Gradio
  Projects/AIML-DATA-SCIENCE-PROJECTS/toxicity-grader-using-deep-learning /README.md
  Projects/AIML-DATA-SCIENCE-PROJECTS/toxicity-grader-using-deep-learning/.gitattributes
  Projects/AIML-DATA-SCIENCE-PROJECTS/toxicity-grader-using-deep-learning/toxicity-grader.ipynb
  Projects/AIML-DATA-SCIENCE-PROJECTS/toxicity-grader-using-deep-learning/toxicity_grader.h5
Labels: good first issue, hacktoberfest-accepted

#45 Tic-Tac-Toe Game
  Projects/Tic-Tac-Toe/README.md
  Projects/Tic-Tac-Toe/index.html
  Projects/Tic-Tac-Toe/package-lock.json
  Projects/Tic-Tac-Toe/package.json
  Projects/Tic-Tac-Toe/public/vite.svg
  Projects/Tic-Tac-Toe/src/App.css
  Projects/Tic-Tac-Toe/src/App.jsx
  Projects/Tic-Tac-Toe/src/components/Assets/circle.png
  Projects/Tic-Tac-Toe/src/components/Assets/cross.png
  Projects/Tic-Tac-Toe/src/components/Tictactoe/Tictactoe.css
  Projects/Tic-Tac-Toe/src/components/Tictactoe/Tictactoe.jsx
  Projects/Tic-Tac-Toe/src/index.css
  Projects/Tic-Tac-Toe/src/main.jsx
  Projects/Tic-Tac-Toe/vite.config.js
Labels: good first issue, hacktoberfest-accepted

#47 Created Fidget Spinner using python
  Projects/fidget spinner.ipynb
Labels: good first issue, hacktoberfest-accepted

#50 Fidget-Spinner
  Projects/fidget spinner.ipynb
Labels: good first issue, hacktoberfest-accepted

#54 Dice-Game
  Projects/Dicegame/README.md
  Projects/Dicegame/dist/assets/index-77fc0aaf.css
  Projects/Dicegame/dist/assets/index-f85cac86.js
  Projects/Dicegame/dist/images/dice/dice_1.png
  Projects/Dicegame/dist/images/dice/dice_2.png
  Projects/Dicegame/dist/images/dice/dice_3.png
  Projects/Dicegame/dist/images/dice/dice_4.png
  Projects/Dicegame/dist/images/dice/dice_5.png
  Projects/Dicegame/dist/images/dice/dice_6.png
  Projects/Dicegame/dist/images/dices 1.png
  Projects/Dicegame/dist/index.html
  Projects/Dicegame/dist/topdice.png
  Projects/Dicegame/index.html
  Projects/Dicegame/package-lock.json
  Projects/Dicegame/package.json
  Projects/Dicegame/public/images/dice/dice_1.png
  Projects/Dicegame/public/images/dice/dice_2.png
  Projects/Dicegame/public/images/dice/dice_3.png
  Projects/Dicegame/public/images/dice/dice_4.png
  Projects/Dicegame/public/images/dice/dice_5.png
  Projects/Dicegame/public/images/dice/dice_6.png
  Projects/Dicegame/public/images/dices 1.png
  Projects/Dicegame/public/topdice.png
  Projects/Dicegame/src/App.css
  Projects/Dicegame/src/App.jsx
  Projects/Dicegame/src/components/Mainscreen.jsx
  Projects/Dicegame/src/components/Numberselector.jsx
  Projects/Dicegame/src/components/Rolldice.jsx
  Projects/Dicegame/src/components/Rules.jsx
  Projects/Dicegame/src/components/Score.jsx
  Projects/Dicegame/src/components/Startgame.css
  Projects/Dicegame/src/components/Startgame.jsx
  Projects/Dicegame/src/index.css
  Projects/Dicegame/src/main.jsx
  Projects/Dicegame/src/rolldice.json
  Projects/Dicegame/src/styled/Button.js
  Projects/Dicegame/vite.config.js
Labels: good first issue, hacktoberfest-accepted

#58 Book-Store
  Projects/book store/c&n.png
  Projects/book store/dsc.png
  Projects/book store/egl.png
  Projects/book store/electricalengineering.png
  Projects/book store/index.html
  Projects/book store/loader-img.gif
  Projects/book store/math.png
  Projects/book store/math2.png
  Projects/book store/mechanics.png
  Projects/book store/mobilecommunication.png
  Projects/book store/phy.png
  Projects/book store/script.js
  Projects/book store/se.png
  Projects/book store/stand.png
  Projects/book store/styles.css
  Projects/book store/toc.png
Labels: good first issue, hacktoberfest-accepted

#59 To-do-list
  Projects/to-do-list/index.html
  Projects/to-do-list/script.js
  Projects/to-do-list/style.css
Labels: good first issue, hacktoberfest-accepted

#69 Weather-App
  Projects/Project5/README.md
  Projects/Project5/index.html
  Projects/Project5/package-lock.json
  Projects/Project5/package.json
  Projects/Project5/public/vite.svg
  Projects/Project5/src/App.css
  Projects/Project5/src/App.jsx
  Projects/Project5/src/assets/cloudy.png
  Projects/Project5/src/assets/drizzle.png
  Projects/Project5/src/assets/humidity.png
  Projects/Project5/src/assets/rain.png
  Projects/Project5/src/assets/search.png
  Projects/Project5/src/assets/snow.png
  Projects/Project5/src/assets/sunny.png
  Projects/Project5/src/assets/windy.png
  Projects/Project5/src/components/WeatherApp.css
  Projects/Project5/src/components/WeatherApp.jsx
  Projects/Project5/src/index.css
  Projects/Project5/src/main.jsx
  Projects/Project5/vite.config.js
Labels: good first issue, hacktoberfest-accepted

#79 Updating README.md for toxicity grader.
  Projects/AIML-DATA-SCIENCE-PROJECTS/toxicity-grader-using-deep-learning/README.md
Labels: documentation, hacktoberfest-accepted

#81 ASD Screening Project
  Projects/AIML-DATA-SCIENCE-PROJECTS/Autism_Detection_using_Machine_Learning/Autism_Detection_Report.pdf
  Projects/AIML-DATA-SCIENCE-PROJECTS/Autism_Detection_using_Machine_Learning/README.md
  Projects/AIML-DATA-SCIENCE-PROJECTS/Autism_Detection_using_Machine_Learning/autism_data.csv
  Projects/AIML-DATA-SCIENCE-PROJECTS/Autism_Detection_using_Machine_Learning/autism_detection.ipynb
  Projects/AIML-DATA-SCIENCE-PROJECTS/Autism_Detection_using_Machine_Learning/boy-playing-with-blocks.jpg
  Projects/AIML-DATA-SCIENCE-PROJECTS/Autism_Detection_using_Machine_Learning/visuals.py
Labels: good first issue, hacktoberfest-accepted
